/*
 * This file is auto-generated. Modifications will be lost.
 *
 * See https://android.googlesource.com/platform/bionic/+/master/libc/kernel/
 * for more information.
 */
#ifndef _UAPI_LINUX_ETHTOOL_NETLINK_H_
#define _UAPI_LINUX_ETHTOOL_NETLINK_H_
#include <linux/ethtool.h>
#include <linux/ethtool_netlink_generated.h>
#define ETHTOOL_FLAG_ALL (ETHTOOL_FLAG_COMPACT_BITSETS | ETHTOOL_FLAG_OMIT_REPLY | ETHTOOL_FLAG_STATS)
enum {
  ETHTOOL_A_CABLE_RESULT_CODE_UNSPEC,
  ETHTOOL_A_CABLE_RESULT_CODE_OK,
  ETHTOOL_A_CABLE_RESULT_CODE_OPEN,
  ETHTOOL_A_CABLE_RESULT_CODE_SAME_SHORT,
  ETHTOOL_A_CABLE_RESULT_CODE_CROSS_SHORT,
  ETHTOOL_A_CABLE_RESULT_CODE_IMPEDANCE_MISMATCH,
  ETHTOOL_A_CABLE_RESULT_CODE_NOISE,
  ETHTOOL_A_CABLE_RESULT_CODE_RESOLUTION_NOT_POSSIBLE,
};
enum {
  ETHTOOL_A_CABLE_PAIR_A,
  ETHTOOL_A_CABLE_PAIR_B,
  ETHTOOL_A_CABLE_PAIR_C,
  ETHTOOL_A_CABLE_PAIR_D,
};
enum {
  ETHTOOL_A_CABLE_INF_SRC_UNSPEC,
  ETHTOOL_A_CABLE_INF_SRC_TDR,
  ETHTOOL_A_CABLE_INF_SRC_ALCD,
};
enum {
  ETHTOOL_A_CABLE_TEST_NTF_STATUS_UNSPEC,
  ETHTOOL_A_CABLE_TEST_NTF_STATUS_STARTED,
  ETHTOOL_A_CABLE_TEST_NTF_STATUS_COMPLETED
};
enum {
  ETHTOOL_A_CABLE_AMPLITUDE_UNSPEC,
  ETHTOOL_A_CABLE_AMPLITUDE_PAIR,
  ETHTOOL_A_CABLE_AMPLITUDE_mV,
  __ETHTOOL_A_CABLE_AMPLITUDE_CNT,
  ETHTOOL_A_CABLE_AMPLITUDE_MAX = (__ETHTOOL_A_CABLE_AMPLITUDE_CNT - 1)
};
enum {
  ETHTOOL_A_CABLE_PULSE_UNSPEC,
  ETHTOOL_A_CABLE_PULSE_mV,
  __ETHTOOL_A_CABLE_PULSE_CNT,
  ETHTOOL_A_CABLE_PULSE_MAX = (__ETHTOOL_A_CABLE_PULSE_CNT - 1)
};
enum {
  ETHTOOL_A_CABLE_STEP_UNSPEC,
  ETHTOOL_A_CABLE_STEP_FIRST_DISTANCE,
  ETHTOOL_A_CABLE_STEP_LAST_DISTANCE,
  ETHTOOL_A_CABLE_STEP_STEP_DISTANCE,
  __ETHTOOL_A_CABLE_STEP_CNT,
  ETHTOOL_A_CABLE_STEP_MAX = (__ETHTOOL_A_CABLE_STEP_CNT - 1)
};
enum {
  ETHTOOL_A_CABLE_TDR_NEST_UNSPEC,
  ETHTOOL_A_CABLE_TDR_NEST_STEP,
  ETHTOOL_A_CABLE_TDR_NEST_AMPLITUDE,
  ETHTOOL_A_CABLE_TDR_NEST_PULSE,
  __ETHTOOL_A_CABLE_TDR_NEST_CNT,
  ETHTOOL_A_CABLE_TDR_NEST_MAX = (__ETHTOOL_A_CABLE_TDR_NEST_CNT - 1)
};
enum {
  ETHTOOL_STATS_ETH_PHY,
  ETHTOOL_STATS_ETH_MAC,
  ETHTOOL_STATS_ETH_CTRL,
  ETHTOOL_STATS_RMON,
  ETHTOOL_STATS_PHY,
  __ETHTOOL_STATS_CNT
};
enum {
  ETHTOOL_A_STATS_ETH_PHY_5_SYM_ERR,
  __ETHTOOL_A_STATS_ETH_PHY_CNT,
  ETHTOOL_A_STATS_ETH_PHY_MAX = (__ETHTOOL_A_STATS_ETH_PHY_CNT - 1)
};
enum {
  ETHTOOL_A_STATS_ETH_MAC_2_TX_PKT,
  ETHTOOL_A_STATS_ETH_MAC_3_SINGLE_COL,
  ETHTOOL_A_STATS_ETH_MAC_4_MULTI_COL,
  ETHTOOL_A_STATS_ETH_MAC_5_RX_PKT,
  ETHTOOL_A_STATS_ETH_MAC_6_FCS_ERR,
  ETHTOOL_A_STATS_ETH_MAC_7_ALIGN_ERR,
  ETHTOOL_A_STATS_ETH_MAC_8_TX_BYTES,
  ETHTOOL_A_STATS_ETH_MAC_9_TX_DEFER,
  ETHTOOL_A_STATS_ETH_MAC_10_LATE_COL,
  ETHTOOL_A_STATS_ETH_MAC_11_XS_COL,
  ETHTOOL_A_STATS_ETH_MAC_12_TX_INT_ERR,
  ETHTOOL_A_STATS_ETH_MAC_13_CS_ERR,
  ETHTOOL_A_STATS_ETH_MAC_14_RX_BYTES,
  ETHTOOL_A_STATS_ETH_MAC_15_RX_INT_ERR,
  ETHTOOL_A_STATS_ETH_MAC_18_TX_MCAST,
  ETHTOOL_A_STATS_ETH_MAC_19_TX_BCAST,
  ETHTOOL_A_STATS_ETH_MAC_20_XS_DEFER,
  ETHTOOL_A_STATS_ETH_MAC_21_RX_MCAST,
  ETHTOOL_A_STATS_ETH_MAC_22_RX_BCAST,
  ETHTOOL_A_STATS_ETH_MAC_23_IR_LEN_ERR,
  ETHTOOL_A_STATS_ETH_MAC_24_OOR_LEN,
  ETHTOOL_A_STATS_ETH_MAC_25_TOO_LONG_ERR,
  __ETHTOOL_A_STATS_ETH_MAC_CNT,
  ETHTOOL_A_STATS_ETH_MAC_MAX = (__ETHTOOL_A_STATS_ETH_MAC_CNT - 1)
};
enum {
  ETHTOOL_A_STATS_ETH_CTRL_3_TX,
  ETHTOOL_A_STATS_ETH_CTRL_4_RX,
  ETHTOOL_A_STATS_ETH_CTRL_5_RX_UNSUP,
  __ETHTOOL_A_STATS_ETH_CTRL_CNT,
  ETHTOOL_A_STATS_ETH_CTRL_MAX = (__ETHTOOL_A_STATS_ETH_CTRL_CNT - 1)
};
enum {
  ETHTOOL_A_STATS_RMON_UNDERSIZE,
  ETHTOOL_A_STATS_RMON_OVERSIZE,
  ETHTOOL_A_STATS_RMON_FRAG,
  ETHTOOL_A_STATS_RMON_JABBER,
  __ETHTOOL_A_STATS_RMON_CNT,
  ETHTOOL_A_STATS_RMON_MAX = (__ETHTOOL_A_STATS_RMON_CNT - 1)
};
enum {
  ETHTOOL_A_STATS_PHY_RX_PKTS,
  ETHTOOL_A_STATS_PHY_RX_BYTES,
  ETHTOOL_A_STATS_PHY_RX_ERRORS,
  ETHTOOL_A_STATS_PHY_TX_PKTS,
  ETHTOOL_A_STATS_PHY_TX_BYTES,
  ETHTOOL_A_STATS_PHY_TX_ERRORS,
  __ETHTOOL_A_STATS_PHY_CNT,
  ETHTOOL_A_STATS_PHY_MAX = (__ETHTOOL_A_STATS_PHY_CNT - 1)
};
#define ETHTOOL_MCGRP_MONITOR_NAME "monitor"
#endif
