/*
 * This file is auto-generated. Modifications will be lost.
 *
 * See https://android.googlesource.com/platform/bionic/+/master/libc/kernel/
 * for more information.
 */
#ifndef _UAPI_LINUX_NET_SHAPER_H
#define _UAPI_LINUX_NET_SHAPER_H
#define NET_SHAPER_FAMILY_NAME "net-shaper"
#define NET_SHAPER_FAMILY_VERSION 1
enum net_shaper_scope {
  NET_SHAPER_SCOPE_UNSPEC,
  NET_SHAPER_SCOPE_NETDEV,
  NET_SHAPER_SCOPE_QUEUE,
  NET_SHAPER_SCOPE_NODE,
  __NET_SHAPER_SCOPE_MAX,
  NET_SHAPER_SCOPE_MAX = (__NET_SHAPER_SCOPE_MAX - 1)
};
enum net_shaper_metric {
  NET_SHAPER_METRIC_BPS,
  NET_SHAPER_METRIC_PPS,
};
enum {
  NET_SHAPER_A_HANDLE = 1,
  NET_SHAPER_A_METRIC,
  NET_SHAPER_A_BW_MIN,
  NET_SHAPER_A_BW_MAX,
  NET_SHAPER_A_BURST,
  NET_SHAPER_A_PRIORITY,
  NET_SHAPER_A_WEIGHT,
  NET_SHAPER_A_IFINDEX,
  NET_SHAPER_A_PARENT,
  NET_SHAPER_A_LEAVES,
  __NET_SHAPER_A_MAX,
  NET_SHAPER_A_MAX = (__NET_SHAPER_A_MAX - 1)
};
enum {
  NET_SHAPER_A_HANDLE_SCOPE = 1,
  NET_SHAPER_A_HANDLE_ID,
  __NET_SHAPER_A_HANDLE_MAX,
  NET_SHAPER_A_HANDLE_MAX = (__NET_SHAPER_A_HANDLE_MAX - 1)
};
enum {
  NET_SHAPER_A_CAPS_IFINDEX = 1,
  NET_SHAPER_A_CAPS_SCOPE,
  NET_SHAPER_A_CAPS_SUPPORT_METRIC_BPS,
  NET_SHAPER_A_CAPS_SUPPORT_METRIC_PPS,
  NET_SHAPER_A_CAPS_SUPPORT_NESTING,
  NET_SHAPER_A_CAPS_SUPPORT_BW_MIN,
  NET_SHAPER_A_CAPS_SUPPORT_BW_MAX,
  NET_SHAPER_A_CAPS_SUPPORT_BURST,
  NET_SHAPER_A_CAPS_SUPPORT_PRIORITY,
  NET_SHAPER_A_CAPS_SUPPORT_WEIGHT,
  __NET_SHAPER_A_CAPS_MAX,
  NET_SHAPER_A_CAPS_MAX = (__NET_SHAPER_A_CAPS_MAX - 1)
};
enum {
  NET_SHAPER_CMD_GET = 1,
  NET_SHAPER_CMD_SET,
  NET_SHAPER_CMD_DELETE,
  NET_SHAPER_CMD_GROUP,
  NET_SHAPER_CMD_CAP_GET,
  __NET_SHAPER_CMD_MAX,
  NET_SHAPER_CMD_MAX = (__NET_SHAPER_CMD_MAX - 1)
};
#endif
